/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dashboard;

import domain.Conexion;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rojerusan.RSAnimation;

//0, 174, 239, 1  -  182, 63, 194, 1             1250-650               1060, 650
/**
 *
 * @author andre
 */
public class mainWindow extends javax.swing.JFrame {

    String documento;
    String nombre;
    String apellido;
    /**
     * Creates new form mainWindow
     *
     * @param documento
     */
    public mainWindow(String documento) {
        initComponents();
        this.setTitle("Software para la gestión de Exportación e Importación");
        
        this.documento = documento;
        panelHome ph = new panelHome(this.documento, "xd");
        ph.setSize(1060, 650);
        ph.setLocation(0, 0);

        content.removeAll();
        content.add(ph, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
        selectUser();
    }

    public mainWindow() {

    }

    public final void selectUser(){
        try {
            Conexion con = new Conexion();
            try ( Connection cx = con.getConexion()) {
                String select = "SELECT nombre, apellido FROM test.usuarios WHERE documento = '" + this.documento + "'";
                PreparedStatement ps = cx.prepareStatement(select);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    this.nombre = rs.getString(1);
                    this.apellido = rs.getString(2);
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al seleccionar " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        panelMenu = new dashborads.PanelRound();
        btnHome = new javax.swing.JButton();
        btnCerrarMenu = new javax.swing.JButton();
        btnTabla = new javax.swing.JButton();
        btnRegistrer = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnMisDatos = new javax.swing.JButton();
        btnAccion = new javax.swing.JButton();
        btnDespachados = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondo.setBackground(new java.awt.Color(60, 63, 65));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(30, 30, 30));
        panelMenu.setRoundBottomRight(40);
        panelMenu.setRoundTopRight(40);

        btnHome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome.setText("Inicio");
        btnHome.setBorder(null);
        btnHome.setBorderPainted(false);
        btnHome.setContentAreaFilled(false);
        btnHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHome.setFocusPainted(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnCerrarMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnCerrarMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/boton-cerrar.png"))); // NOI18N
        btnCerrarMenu.setBorder(null);
        btnCerrarMenu.setBorderPainted(false);
        btnCerrarMenu.setContentAreaFilled(false);
        btnCerrarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrarMenu.setFocusPainted(false);
        btnCerrarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarMenuActionPerformed(evt);
            }
        });

        btnTabla.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnTabla.setForeground(new java.awt.Color(255, 255, 255));
        btnTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tabla.png"))); // NOI18N
        btnTabla.setText("Resumen");
        btnTabla.setBorder(null);
        btnTabla.setBorderPainted(false);
        btnTabla.setContentAreaFilled(false);
        btnTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTabla.setFocusPainted(false);
        btnTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaActionPerformed(evt);
            }
        });

        btnRegistrer.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegistrer.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/registrar.png"))); // NOI18N
        btnRegistrer.setText("Registrar");
        btnRegistrer.setBorder(null);
        btnRegistrer.setBorderPainted(false);
        btnRegistrer.setContentAreaFilled(false);
        btnRegistrer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrer.setFocusPainted(false);
        btnRegistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrerActionPerformed(evt);
            }
        });

        btnReportes.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reportesIcon.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(null);
        btnReportes.setBorderPainted(false);
        btnReportes.setContentAreaFilled(false);
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setFocusPainted(false);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });

        btnMisDatos.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnMisDatos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Detalles.png"))); // NOI18N
        btnMisDatos.setText("Cuenta");
        btnMisDatos.setBorder(null);
        btnMisDatos.setBorderPainted(false);
        btnMisDatos.setContentAreaFilled(false);
        btnMisDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisDatos.setFocusPainted(false);
        btnMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisDatosActionPerformed(evt);
            }
        });

        btnAccion.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnAccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hacer-clic.png"))); // NOI18N
        btnAccion.setText("Acciones");
        btnAccion.setBorder(null);
        btnAccion.setBorderPainted(false);
        btnAccion.setContentAreaFilled(false);
        btnAccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccion.setFocusPainted(false);
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnDespachados.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnDespachados.setForeground(new java.awt.Color(255, 255, 255));
        btnDespachados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/despachados.png"))); // NOI18N
        btnDespachados.setText("Estados");
        btnDespachados.setBorder(null);
        btnDespachados.setBorderPainted(false);
        btnDespachados.setContentAreaFilled(false);
        btnDespachados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDespachados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDespachadosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrarSeson.png"))); // NOI18N
        btnSalir.setText("Cerrar Sesion");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusPainted(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir)
                    .addComponent(btnHome)
                    .addComponent(btnTabla)
                    .addComponent(btnRegistrer)
                    .addComponent(btnReportes)
                    .addComponent(btnAccion)
                    .addComponent(btnDespachados)
                    .addComponent(btnMisDatos))
                .addGap(12, 12, 12))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(btnCerrarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnRegistrer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnReportes)
                .addGap(58, 58, 58)
                .addComponent(btnAccion)
                .addGap(54, 54, 54)
                .addComponent(btnDespachados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnMisDatos)
                .addGap(40, 40, 40)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelFondo.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, 0, 190, 650));

        btnMenu.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setFocusPainted(false);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        panelFondo.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        content.setBackground(new java.awt.Color(60, 63, 65));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        panelFondo.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1060, 650));

        getContentPane().add(panelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        RSAnimation.setMoverDerecha(-190, 0, 2, 2, panelMenu);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCerrarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarMenuActionPerformed
        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnCerrarMenuActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        panelHome ph = new panelHome(this.documento,"xd");
        ph.setSize(1060, 650);
        ph.setLocation(0, 0);

        content.removeAll();
        content.add(ph, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaActionPerformed
        panelResumen pt = new panelResumen();
        pt.setSize(1060, 650);
        pt.setLocation(0, 0);

        content.removeAll();
        content.add(pt, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnTablaActionPerformed

    private void btnRegistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrerActionPerformed
        panelForm pf = new panelForm(this.nombre, this.apellido);
        pf.setSize(1060, 650);
        pf.setLocation(0, 0);

        content.removeAll();
        content.add(pf, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnRegistrerActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        panelReportes pr = new panelReportes();
        pr.setSize(1060, 650);
        pr.setLocation(0, 0);

        content.removeAll();
        content.add(pr, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisDatosActionPerformed
        panelMisDatos pc = new panelMisDatos(this.documento);
        pc.setSize(1060, 650);
        pc.setLocation(0, 0);

        content.removeAll();
        content.add(pc, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnMisDatosActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        panelAction pa = new panelAction();
        pa.setSize(1060, 650);
        pa.setLocation(0, 0);

        content.removeAll();
        content.add(pa, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnDespachadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDespachadosActionPerformed
        panelEstados pd = new panelEstados();
        pd.setSize(1060, 650);
        pd.setLocation(0, 0);

        content.removeAll();
        content.add(pd, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

        RSAnimation.setMoverIzquierda(0, -190, 2, 2, panelMenu);
    }//GEN-LAST:event_btnDespachadosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException //
     */
//    public static void main(String args[]) throws UnsupportedLookAndFeelException {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        UIManager.setLookAndFeel(new FlatIntelliJLaf());
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new mainWindow().setVisible(true);
//            }
//        });
//    }
    //0, 174, 239, 1  -  182, 63, 194, 1             1250-650               1060, 650
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnCerrarMenu;
    private javax.swing.JButton btnDespachados;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMisDatos;
    private javax.swing.JButton btnRegistrer;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTabla;
    private javax.swing.JPanel content;
    private javax.swing.JPanel panelFondo;
    private dashborads.PanelRound panelMenu;
    // End of variables declaration//GEN-END:variables
}
