/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Login;

import dashboard.mainWindow;
import dashboardCliente.panelCliente;
import domain.Conexion;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author andre
 */
public class Log extends javax.swing.JPanel {

    JPanel panel;

    /**
     * Creates new form Log
     *
     * @param panel
     */
    public Log(JPanel panel) {
        initComponents();
        this.panel = panel;
       
    }

    public void select() {
        Conexion con = new Conexion();
        Connection cx = con.getConexion();
        if ((txtUsuario.getText().isEmpty() || txtContraseña.getPassword().equals(""))) {
            JOptionPane.showMessageDialog(null, "Asegurate de llenar todo los campos");
            return;
        }

        String user = txtUsuario.getText();
        String pass = String.valueOf(txtContraseña.getPassword());
        String SELECT = "SELECT documento, tipo FROM test.usuarios WHERE usuario = '" + user + "' and contraseña = '" + pass + "'";
        String tipe = "";

        String documento = "";

        try {
            try ( PreparedStatement ps = cx.prepareStatement(SELECT)) {
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    documento = rs.getString(1);
                    tipe = rs.getString(2);

                    if (tipe.equals("Cliente")) {
                        panelCliente pc = new panelCliente(documento);
                        pc.setVisible(true);
                    } else {
                        mainWindow mw = new mainWindow(documento);
                        mw.setVisible(true);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "usuario y/o contraseña incorrectos");
                    txtUsuario.setText(null);
                    txtContraseña.setText(null);
                }
            }
            cx.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error sql " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnVerContra = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        txtUsuario = new utilities.TextField();
        txtContraseña = new passwordfield.PasswordField();

        setBackground(new java.awt.Color(40, 40, 40));

        contenido.setBackground(new java.awt.Color(39, 39, 39));
        contenido.setPreferredSize(new java.awt.Dimension(520, 514));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");

        btnVerContra.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnVerContra.setForeground(new java.awt.Color(255, 255, 255));
        btnVerContra.setText("Mostrar Contraseña");
        btnVerContra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVerContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerContraActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Una Cuenta");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        txtUsuario.setBackground(new java.awt.Color(39, 39, 39));
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtUsuario.setShadowColor(new java.awt.Color(0, 204, 255));

        txtContraseña.setBackground(new java.awt.Color(39, 39, 39));
        txtContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txtContraseña.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txtContraseña.setShadowColor(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVerContra)
                            .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton1)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnVerContra)
                .addGap(41, 41, 41)
                .addComponent(btnEntrar)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        select();

    }//GEN-LAST:event_btnEntrarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SignUp su = new SignUp(this.contenido);
        su.setSize(520, 514);
        su.setLocation(0, 0);

        this.contenido.removeAll();
        this.contenido.add(su, BorderLayout.CENTER);
        this.contenido.revalidate();
        this.contenido.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerContraActionPerformed
        if (btnVerContra.isSelected()) {
            txtContraseña.setEchoChar((char) 0);
        } else {
            txtContraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_btnVerContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JCheckBox btnVerContra;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private passwordfield.PasswordField txtContraseña;
    private utilities.TextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
